@extends('layouts.admin')
@section('content')
<x-page-header title="Vue d’ensemble" description="Santé du Control Plane, capacité disponible et événements nécessitant une attention." eyebrow="Administration"/>
<section><h2 class="eyebrow mb-3">Indicateurs prioritaires</h2><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card label="CentralPanel actifs" :value="$stats['projects']['active']"/><x-stat-card label="Nodes en ligne" :value="$stats['nodes']['online']"/><x-stat-card label="Opérations en cours" :value="$stats['operations']['running']"/><x-stat-card label="Incidents ouverts" :value="$stats['incidents']" :tone="$stats['incidents'] ? 'danger' : 'default'"/></div></section>
<section class="mt-8 grid gap-6 xl:grid-cols-3">
    <x-card title="Utilisateurs" description="État global des comptes."><dl class="grid grid-cols-2 gap-5"><div><dt class="data-label">Total</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['users']['total'] }}</dd></div><div><dt class="data-label">Actifs</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['users']['active'] }}</dd></div><div><dt class="data-label">Nouveaux 7 jours</dt><dd class="data-value tabular-nums">{{ $stats['users']['new_7d'] }}</dd></div><div><dt class="data-label">Suspendus</dt><dd class="data-value tabular-nums">{{ $stats['users']['suspended'] }}</dd></div></dl></x-card>
    <x-card title="Déploiements" description="Répartition des états principaux."><dl class="grid grid-cols-2 gap-5"><div><dt class="data-label">Total</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['projects']['total'] }}</dd></div><div><dt class="data-label">En préparation</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['projects']['provisioning'] }}</dd></div><div><dt class="data-label">Arrêtés</dt><dd class="data-value tabular-nums">{{ $stats['projects']['stopped'] }}</dd></div><div><dt class="data-label">Échecs</dt><dd class="data-value tabular-nums text-red-700 dark:text-red-300">{{ $stats['projects']['failed'] }}</dd></div></dl></x-card>
    <x-card title="Facturation" description="Situation des abonnements Stripe."><dl class="grid grid-cols-3 gap-4"><div><dt class="data-label">Actifs</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['billing']['active'] }}</dd></div><div><dt class="data-label">Retard</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['billing']['past_due'] }}</dd></div><div><dt class="data-label">Annulés</dt><dd class="mt-1 text-2xl font-semibold tabular-nums">{{ $stats['billing']['cancelled'] }}</dd></div></dl></x-card>
</section>
<div class="mt-8 grid gap-6 xl:grid-cols-2">
    <x-card title="Capacité des Nodes" description="Utilisation mémoire et espace disque disponible."><div class="divider-list">@forelse($nodes as $node)<div class="py-4 first:pt-0 last:pb-0"><div class="mb-2 flex flex-wrap items-center justify-between gap-2 text-sm"><span class="font-medium">{{ $node->name }}</span><span class="flex items-center gap-3"><x-status-badge :status="$node->status"/><span class="text-slate-500">{{ $node->deployment_count }} déploiements</span></span></div>@php($ram=$node->memory_total_bytes?round(100*(1-$node->memory_available_bytes/$node->memory_total_bytes)):0)<div class="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full rounded-full bg-brand-600" style="width:{{ min(100,max(0,$ram)) }}%"></div></div><p class="mt-2 text-xs text-slate-500">RAM utilisée : {{ $ram }} % · disque libre : {{ round($node->disk_available_bytes/1073741824,1) }} Gio</p></div>@empty<p class="text-sm text-slate-500">Aucun Node enregistré.</p>@endforelse</div></x-card>
    <x-card title="Incidents récents" description="Événements ouverts classés par dernière activité."><div class="divider-list">@forelse($incidents as $incident)<div class="py-4 first:pt-0 last:pb-0"><div class="flex items-center justify-between gap-3"><span class="text-sm font-medium">{{ $incident->source_type }}</span><x-status-badge :status="$incident->severity"/></div><p class="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{{ $incident->message }}</p></div>@empty<div class="py-6 text-center"><x-icon name="check" class="mx-auto text-emerald-600"/><p class="mt-2 text-sm text-slate-500">Aucun incident ouvert.</p></div>@endforelse</div></x-card>
</div>
@endsection
