<?php

return [
    'agent' => [
        'client_cert' => env('CENTRALCLOUD_AGENT_CLIENT_CERT'),
        'client_key' => env('CENTRALCLOUD_AGENT_CLIENT_KEY'),
        'ca_cert' => env('CENTRALCLOUD_AGENT_CA_CERT'),
        'allowed_cidrs' => array_values(array_filter(array_map('trim', explode(',', (string) env('CENTRALCLOUD_AGENT_ALLOWED_CIDRS', ''))))),
        'allowed_ports' => array_map('intval', explode(',', (string) env('CENTRALCLOUD_AGENT_ALLOWED_PORTS', '443,9443'))),
        'connect_timeout' => (int) env('CENTRALCLOUD_AGENT_CONNECT_TIMEOUT', 5),
        'timeout' => (int) env('CENTRALCLOUD_AGENT_TIMEOUT', 20),
    ],
    'panel' => [
        'image' => env('CENTRALPANEL_IMAGE'),
        'domain_suffix' => env('CENTRALPANEL_DOMAIN_SUFFIX', 'panels.centralcloud.fr'),
        'reserved_subdomains' => ['admin', 'api', 'app', 'assets', 'billing', 'dashboard', 'mail', 'status', 'support', 'www'],
        'health_path' => env('CENTRALPANEL_HEALTH_PATH', '/up'),
        'health_timeout' => (int) env('CENTRALPANEL_HEALTH_TIMEOUT', 60),
    ],
    'nodes' => [
        'offline_after_minutes' => (int) env('CENTRALCLOUD_NODE_OFFLINE_AFTER', 35),
        'ram_margin_bytes' => (int) env('CENTRALCLOUD_SCHEDULER_RAM_MARGIN', 536870912),
        'disk_margin_bytes' => (int) env('CENTRALCLOUD_SCHEDULER_DISK_MARGIN', 5368709120),
        'maximum_deployments' => (int) env('CENTRALCLOUD_NODE_MAXIMUM_DEPLOYMENTS', 50),
    ],
    'enrollment' => [
        'enabled' => filter_var(env('CENTRALCLOUD_ENROLLMENT_ENABLED', true), FILTER_VALIDATE_BOOL),
        'installer_url' => env('CENTRALCLOUD_INSTALLER_URL', 'https://install.centralcloud.fr/node'),
        'ttl' => (int) env('CENTRALCLOUD_ENROLLMENT_TTL', 600),
        'poll_interval' => (int) env('CENTRALCLOUD_ENROLLMENT_POLL_INTERVAL', 5),
        'bootstrap_ttl' => (int) env('CENTRALCLOUD_ENROLLMENT_BOOTSTRAP_TTL', 5400),
        'hash_key' => env('CENTRALCLOUD_ENROLLMENT_HASH_KEY'),
        'default_agent_channel' => env('CENTRALCLOUD_DEFAULT_AGENT_CHANNEL', 'stable'),
        'default_agent_version' => env('CENTRALCLOUD_DEFAULT_AGENT_VERSION', '1.3.0'),
        'agent_manifest_url' => env('CENTRALCLOUD_AGENT_MANIFEST_URL'),
        'release_public_key' => env('CENTRALCLOUD_RELEASE_PUBLIC_KEY'),
        'certificate_issuer' => env('CENTRALCLOUD_CERTIFICATE_ISSUER', 'local_ca'),
        'ca_cert_path' => env('CENTRALCLOUD_NODE_CA_CERT_PATH'),
        'ca_key_path' => env('CENTRALCLOUD_NODE_CA_KEY_PATH'),
        'control_plane_client_ca_path' => env('CENTRALCLOUD_CONTROL_PLANE_CLIENT_CA_PATH'),
        'allowed_client_sans' => array_values(array_filter(array_map('trim', explode(',', (string) env('CENTRALCLOUD_ALLOWED_CLIENT_SANS', 'spiffe://centralcloud/control-plane'))))),
        'source_cidrs' => array_values(array_filter(array_map('trim', explode(',', (string) env('CENTRALCLOUD_CONTROL_PLANE_SOURCE_CIDRS', ''))))),
        'certificate_days' => (int) env('CENTRALCLOUD_NODE_CERTIFICATE_DAYS', 90),
        'agent_port' => (int) env('CENTRALCLOUD_NODE_AGENT_PORT', 9443),
        'dashboard_version' => env('CENTRALCLOUD_DASHBOARD_VERSION', '1.0.0'),
    ],
    'billing' => ['suspension_grace_days' => (int) env('CENTRALCLOUD_PAYMENT_GRACE_DAYS', 7)],
    'webcron' => ['username' => env('CENTRALCLOUD_CRON_USERNAME', 'centralcloud-cron'), 'secret' => env('CENTRALCLOUD_CRON_SECRET')],
];
